spring.application.name=BankingManagementSystem
spring.datasource.url=jdbc:mysql://localhost:3306/bankdb
spring.datasource.username=root
spring.datasource.password=Nikhil123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true